stages:
  - build
  - docker
  - update-values

variables:
  IMAGE_NAME: "rushi2323/petclinic-app"
  IMAGE_TAG: "git-${CI_COMMIT_SHORT_SHA}"
  HELM_REPO_URL: "https://gitlab.com/rushimane2606-group/monitoring-all-tools.git"
  HELM_CHART_PATH: "helm/petclinic"
  GIT_AUTHOR_NAME: "GitLab CI"
  GIT_AUTHOR_EMAIL: "ci@gitlab.com"

# ----------------------------
# 1) Build the Spring Boot JAR
# ----------------------------
build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn -B clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - dev   # dev branch -> will map to test cluster
    - main  # main branch -> will map to prod cluster

# ----------------------------
# 2) Build & push Docker image
# ----------------------------
docker_build:
  stage: docker
  image: docker:24.0.2
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - dev
    - main

# ----------------------------
# 3) Update Helm values in the GitOps repo (rushi2606) so ArgoCD can deploy
# ----------------------------
update_helm_values:
  stage: update-values
  image: alpine:3.18
  before_script:
    - apk add --no-cache git curl bash
    - curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq && chmod +x /usr/bin/yq
    - git config --global user.name "$GIT_AUTHOR_NAME"
    - git config --global user.email "$GIT_AUTHOR_EMAIL"
  script:
    - echo "Cloning Helm/GitOps repo..."
    - git clone "$HELM_REPO_URL" helm-repo
    - cd helm-repo/$HELM_CHART_PATH
    # decide which values file to update based on branch
    - |
      if [ "$CI_COMMIT_BRANCH" = "dev" ]; then
        FILE="values-test.yaml"
      elif [ "$CI_COMMIT_BRANCH" = "main" ]; then
        FILE="values-prod.yaml"
      else
        echo "Branch $CI_COMMIT_BRANCH not mapped to an env - defaulting to values-test.yaml"
        FILE="values-test.yaml"
      fi
    - echo "Updating $FILE with image $IMAGE_NAME:$IMAGE_TAG"
    - yq e -i ".image.repository = \"$IMAGE_NAME\"" $FILE
    - yq e -i ".image.tag = \"$IMAGE_TAG\"" $FILE
    - git add $FILE
    - |
      if git diff --staged --quiet; then
        echo "No changes to commit."
      else
        git commit -m "ci: update $FILE image -> $IMAGE_TAG from $CI_PROJECT_PATH@$CI_COMMIT_SHORT_SHA"
        # push via token: repo must allow this PAT to push to main
        git push https://oauth2:${GITLAB_TOKEN}@gitlab.com/rushimane2606-group/monitoring-all-tools.git HEAD:main
      fi
  only:
    - dev
    - main
